### ISSUE TITLE
抱歉，打扰一下

### ISSUE THREAD

**Issue by ImportMengjie** [seefun/NAIC_baseline_pytorch#1]
你好，我是北邮的研究生，错过了这个比赛的报名

想有偿的问问你关于AI+无线通信比赛的一些问题（比赛的一些细节、分享一下看过的论文等）和比赛数据分享

我的导师让我根据这个比赛做毕设。

如果可以的话加一下我的微信：ImportMengjie 

万分感谢Thanks♪(･ω･)ﾉ

**Comment by seefun** [comment]
1. 初赛baseline开源在主文件夹，复赛baseline代码（不可靠）开源在tmp文件夹，可以参考引用。最终版代码由于分数不高暂时不开源了。
2. 关于比赛数据的获取，可以咨询比赛主办方，寻求数据权限。私下的数据分享不被允许。
3. 关于比赛细节可自行阅读代码，论文推荐[金石教授的一些论文](https://scholar.google.com/citations?user=xGkd6qwAAAAJ&hl=zh-CN&oi=sra)
4. 本人不是通信方向，可能无法解答更多问题，表示抱歉

**Comment by ImportMengjie** [comment]
谢谢了！

**Comment by seefun** [comment]
> 谢谢了！

关于开源代码的问题可以随时在群里或者issue里提出，尽量解答（无偿），点点star和follow就行 :-)
