### ISSUE TITLE
整个工程完整吗？

### ISSUE THREAD

**Issue by 18hfliu** [seefun/NAIC_baseline_pytorch#2]
能否提供训练集和测试集呢？
有encoder类与decoder类吗？

**Comment by seefun** [comment]
1. 由于数据授权缘故，数据集可从比赛链接中从比赛主办方获取。https://www.datafountain.cn/competitions/455/ 
2. 工程完整, Model_define_pytorch.py Model_train.py两个文件即为完整工程，encoder decoder设计请看具体代码。

**Comment by 18hfliu** [comment]
谢谢，不过我没有报名，无法从比赛主办方获取数据。目前也无法报名了。

**Comment by seefun** [comment]
> 谢谢，不过我没有报名，无法从比赛主办方获取数据。目前也无法报名了。

据说今年还有同类数据的新比赛即将放出
